---
title: "Data Challenge 4"
author: "Nage Ngo, Carol Milton, Esa Schenck"
date: "3/24/2021"
output:   
  html_document:
    toc: true
    toc_depth: 3
    theme: cosmo
    highlight: tango
    toc_float: true
    code_folding: hide
---

```{r set up, include = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, error = F)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(plotly)
library(scales)
```

# Connecting to Database Server
```{r}
#i looked at https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html#introduction
#BUT this is from https://www.datacareer.de/blog/connect-to-postgresql-with-r-a-step-by-step-example/

#You need to have RPostgreSQL and RPostgres installed for this

#con<-dbConnect(RPostgres::Postgres())

library(RMySQL)
library(DBI)
```
```{r}
db <- 'postgres'  #provide the name of your db

host_db <- 'database-dc4.cimcghmqvw06.us-east-2.rds.amazonaws.com'  

db_port <- 5432  # or any other port specified by the DBA

db_user <- 'dc4'

db_password <- 'password'

con <- dbConnect(RPostgres::Postgres(), dbname = db, 
                 host=host_db, port=db_port, user=db_user, password=db_password)
#db
#host_db
#db_port
#db_user
#db_password
```

```{r}
# from https://www.datacareer.de/blog/connect-to-postgresql-with-r-a-step-by-step-example/

dbListTables(con)
##IT WORKS!!!
```

```{r}
firewall_0406_trial <- read_csv("Firewall-04072012.csv") %>% head(60)
```

```{r}
#from https://www.r-bloggers.com/2016/02/using-postgresql-in-r-a-quick-how-to/
dbWriteTable(con,'trial_0406',firewall_0406_trial, row.names=FALSE)
dbListTables(con)
dbReadTable(con, "trial_0406")
```

```{r}
#Now to ACTUALLY put these into the database!!
#firewall_0406_csv <- read_csv("Firewall-04062012.csv")
#dbWriteTable(con,'firewall_0406', firewall_0406_csv, row.names=FALSE, overwrite = TRUE)
```

```{r}
#firewall_0407_csv <- read_csv("Firewall-04072012.csv")
#dbWriteTable(con,'firewall_0407', firewall_0407_csv, row.names=FALSE)
```

```{r}
#Check if it worked
#dbReadTable(con, 'firewall_0407')
#IT WORKED Commenting it out b/c it took a lot of time to run
```


```{r}
#I'm taking the first 600,000 rows of the firewall data because these are MASSIVE files and R will crash. I'm thinking once we're sure what we're going to do and have done some exploratory stuff, then we can make R do it with the full rows and be prepared for it to take a while (or alternatively we can use tableau, or think about using a database)

#The lines to read the firewall dataframs were commented out after the database was set up

#firewall_0406_short <- read_csv("Firewall-04062012.csv") %>% head(600000)
#firewall_0407_short <- read_csv("Firewall-04072012.csv") %>% head(600000)

ids_0406 <- read_csv("IDS-0406-updated.csv")
ids_0407 <- read_csv("IDS-0407.csv")
```




# Firewall 

```{r}
Firewall_04072012 <- readr::read_csv("DC4-data/Firewall/Firewall-04072012.csv")
```


```{r}
Firewall_a <- Firewall_04072012 %>% 
  mutate(hour = substr(`Date/time`,12,14),
         n = 1,
         date = substr(`Date/time`,1,2)) 
DNS_root <- c("198.41.0.4", "128.9.0.107", "192.33.4.12", "128.8.10.90", "192.203.230.10", "192.5.5.241",
              "192.112.36.4", "128.63.2.53", "192.36.148.17", "192.58.128.30", "193.0.14.129",
              "198.32.64.12", "202.12.27.33", "172.23.0.10")
firewall_id_DNS_root <- Firewall_a %>%
  filter(str_detect(`Destination IP`,DNS_root)|str_detect(`Destination IP`,DNS_root))

cisco_ASA <- c( "10.32.2.100", "10.32.2.101", "172.23.0.1")
firewall_id_cisco <- Firewall_a %>%
  filter(`Destination IP`=="10.32.0.1"|str_detect(`Source IP`,cisco_ASA)|           str_detect(`Destination IP`,cisco_ASA))

firewall_id_corp <- Firewall_a %>%
  filter(`Destination IP`==  "172.25.0.1"|`Source IP`==  "172.25.0.1"|`Source IP`==  "10.32.0.100"|`Destination IP`==  "10.32.0.100")
# 06/Apr/2012 18:06:42	

website <- c("10.32.0.2", "10.32.1.100", "10.32.1.20", "10.32.5.1")
firewall_id_web <- Firewall_a %>%
  filter(str_detect(`Destination IP`,website)|str_detect(`Destination IP`,website))

```

# Network 

## General / Sample 10%

```{r}
set.seed(2021)
sample_fire <- dplyr::sample_frac(Firewall_04072012, 0.1) 
netw <- sample_fire %>% select(`Source IP`, `Destination IP`)
#node list
sources <- netw %>% distinct(`Source IP`) %>% rename( id = `Source IP`) %>% mutate(from = "from")
destinations <- netw %>% distinct(`Destination IP`) %>% rename(id = `Destination IP`)
nodes <- full_join(sources, destinations, by = "id") %>% distinct(id,.keep_all=T) #%>% 
  # mutate(f = ifelse(from=="from", "from", "to")) %>% select(id,f)

#edge list
per_route <- netw %>%  
  group_by(`Source IP`, `Destination IP`) %>%
  summarise(weight = n()) %>% arrange(desc(weight)) %>%
  ungroup()
edges <- per_route %>% 
  left_join(nodes, by = c(`Source IP` = "id"))
edges <- edges %>% 
  left_join(nodes, by = c(`Destination IP` = "id"))
edges <- select(edges, from = `Source IP`, to = `Destination IP`, weight) 

```

```{r}
# A tbl_graph consists of two tibbles: an edges tibble and a nodes tibble
routes_tidy <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE) 

nw <- ggraph(routes_tidy, layout = "graphopt") +
  geom_edge_link(aes(color = weight, width = weight), alpha = 0.7) +
  scale_edge_width(range = c(0.2, 2)) +
  scale_edge_colour_gradient(low = "#b9b0f7",
                             high = "black",
                             space = "Lab") +
  geom_node_point(colour = "#635d5d", alpha = 0.5 )+ #aes(colour = ifelse(f=="from" ,"#0f0fa3","#635d5d")), show.legend = FALSE) +
  theme_graph() #+
  # geom_node_text(aes(label = ifelse(f=="from", id, NA)), repel = TRUE)

nw
```


## Cisco

```{r}
netw <- firewall_id_cisco %>% select(`Source IP`, `Destination IP`)
#node list
sources <- netw %>% distinct(`Source IP`) %>% rename( id = `Source IP`) %>% mutate(from = "from")
destinations <- netw %>% distinct(`Destination IP`) %>% rename(id = `Destination IP`)
nodes <- full_join(sources, destinations, by = "id") %>% distinct(id,.keep_all=T) #%>% 
  # mutate(f = ifelse(from=="from", "from", "to")) %>% select(id,f)

#edge list
per_route <- netw %>%  
  group_by(`Source IP`, `Destination IP`) %>%
  summarise(weight = n()) %>% arrange(desc(weight)) %>%
  ungroup()
edges <- per_route %>% 
  left_join(nodes, by = c(`Source IP` = "id"))
edges <- edges %>% 
  left_join(nodes, by = c(`Destination IP` = "id"))
edges <- select(edges, from = `Source IP`, to = `Destination IP`, weight) 

```

```{r}
# A tbl_graph consists of two tibbles: an edges tibble and a nodes tibble
routes_tidy1 <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE) 

nw1 <- ggraph(routes_tidy1, layout = "graphopt") +
  geom_node_point(colour = "#635d5d", alpha = 0.5 )+ #aes(colour = ifelse(f=="from" ,"#0f0fa3","#635d5d")), show.legend = FALSE) +
  geom_edge_link(aes(color = weight, width = weight), alpha = 0.7) +
  scale_edge_width(range = c(0.2, 2)) +
  scale_edge_colour_gradient(low = "#b9b0f7",
                             high = "black",
                             space = "Lab") +
  theme_graph() #+
  # geom_node_text(aes(label = ifelse(f=="from", id, NA)), repel = TRUE)

nw1
```

## corporate 

```{r}
netw <- firewall_id_corp %>% select(`Source IP`, `Destination IP`)
#node list
sources <- netw %>% distinct(`Source IP`) %>% rename( id = `Source IP`) %>% mutate(from = "from")
destinations <- netw %>% distinct(`Destination IP`) %>% rename(id = `Destination IP`)
nodes <- full_join(sources, destinations, by = "id") %>% distinct(id,.keep_all=T) #%>% 
  # mutate(f = ifelse(from=="from", "from", "to")) %>% select(id,f)

#edge list
per_route <- netw %>%  
  group_by(`Source IP`, `Destination IP`) %>%
  summarise(weight = n()) %>% arrange(desc(weight)) %>%
  ungroup()
edges <- per_route %>% 
  left_join(nodes, by = c(`Source IP` = "id"))
edges <- edges %>% 
  left_join(nodes, by = c(`Destination IP` = "id"))
edges <- select(edges, from = `Source IP`, to = `Destination IP`, weight) 

```

```{r}
# A tbl_graph consists of two tibbles: an edges tibble and a nodes tibble
routes_tidy2 <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE) 

nw2 <- ggraph(routes_tidy2, layout = "graphopt") +
  geom_node_point(colour = "#635d5d", alpha = 0.5 )+ #aes(colour = ifelse(f=="from" ,"#0f0fa3","#635d5d")), show.legend = FALSE) +
  geom_edge_link(aes(color = weight, width = weight), alpha = 0.7) +
  scale_edge_width(range = c(0.2, 2)) +
  scale_edge_colour_gradient(low = "#b9b0f7",
                             high = "black",
                             space = "Lab") +
  theme_graph() #+
  # geom_node_text(aes(label = ifelse(f=="from", id, NA)), repel = TRUE)

nw2
```

# Activity

```{r}
Firewall_a_06 <- Firewall_a%>% filter(str_detect(`Date/time`, "06/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))
Firewall_a_07 <- Firewall_a%>% filter(str_detect(`Date/time`, "07/Apr/2012"))%>%
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T)%>% 
  select(c(hour, count))



a1 <- ggplot(Firewall_a_06, aes(x = as.integer(hour), y = count)) + geom_line() + theme_classic() +
  scale_y_continuous(labels = comma, limits = c(0,850000)) + labs(title = "Hourly Activity on April 6") +
  scale_x_continuous(name="Hour", breaks = c(17:23))
a2 <- ggplot(Firewall_a_07, aes(x = as.integer(hour), y = count)) + geom_line() + theme_classic() +
  scale_y_continuous(labels = comma, limits = c(0,850000)) + labs(title = "Hourly Activity on April 7")+
  scale_x_continuous(name="Hour", breaks = c(0:9))

ggpubr::ggarrange(a1,a2, ncol = 2) #, common.legend = TRUE, legend="bottom")
  # datetime = as.POSIXct(str_c(date1, time, sep=" "), format="%D/%M/%Y %H:%M:%S"))
```

**by ID**

```{r}
a_DNS_6 <- firewall_id_DNS_root %>%
  filter(str_detect(`Date/time`, "06/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))
a_DNS_7 <- firewall_id_DNS_root %>%
  filter(str_detect(`Date/time`, "07/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))

a_cisco_ASA_6 <- firewall_id_cisco %>%
  filter(str_detect(`Date/time`, "06/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))
a_cisco_ASA_7 <- firewall_id_cisco %>%
  filter(str_detect(`Date/time`, "07/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))

a_corporate_6 <- firewall_id_corp %>%
  filter(str_detect(`Date/time`, "06/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count))%>%
  full_join(a_cisco_ASA_6, by = "hour")%>%
  full_join(a_DNS_6,  by = "hour") %>% rename(corporate = count.x,
                                              cisco = count.y, 
                                              dns = count)
a_corporate_6[is.na(a_corporate_6)] <- 0
a_corporate_6 <- a_corporate_6 %>% pivot_longer(cols = c(-hour), values_to="count", names_to = "IP")

a_corporate_7 <- firewall_id_corp %>%
  filter(str_detect(`Date/time`, "07/Apr/2012"))%>% 
  group_by(hour) %>% mutate(count = sum(n)) %>% distinct(hour, .keep_all=T) %>% 
  select(c(hour, count)) %>% 
  full_join(a_cisco_ASA_7, by = "hour")%>%
  full_join(a_DNS_7,  by = "hour") %>% rename(corporate = count.x,
                                              cisco = count.y, 
                                              dns = count)
a_corporate_7[is.na(a_corporate_7)] <- 0
a_corporate_7 <- a_corporate_7 %>% pivot_longer(cols = c(-hour), values_to="count", names_to = "IP")


a3 <- ggplot(a_corporate_6, aes(x = as.integer(hour), y = count, color = IP)) + geom_line() +
  theme_classic() +
  # scale_y_continuous(labels = comma, limits = c(0,180000)) +
  labs(title = "Hourly Activity on April 6 by Firewall IPs") +
  scale_x_continuous(name="Hour", breaks = c(17:23))
a4 <- ggplot(a_corporate_7, aes(x = as.integer(hour), y = count, color = IP)) + geom_line() +
  theme_classic() +
  # scale_y_continuous(labels = comma, limits = c(0,180000)) +
  labs(title = "Hourly Activity on April 7 by Firewall IPs", y = NULL)+
  scale_x_continuous(name="Hour", breaks = c(0:9))
ggpubr::ggarrange(a3,a4, ncol = 2 , common.legend = TRUE, legend="bottom")
```

